version: '3.9'

services:
  # hostapi
  hostapi:
    image: registry.cn-hangzhou.aliyuncs.com/learn-zhou/zhou-learn:ke210
    restart: always
    ports:
      - "2001:80"
    networks:
      - my_net
    volumes:
      - "hostapi_logs:/app/App_Data/Logs"
      - "hostapi_sysfiles:/app/wwwroot/SysFiles"
      - "hostapi_fastreport:/app/wwwroot/FastReport"
    environment:
      - App__WebHostPort=80
      - ASPNETCORE_ENVIRONMENT=Production
      - App__ConnectionString__Default=Server=124.71.15.19;Database=NetWiki;MultipleActiveResultSets=true;Uid=sa;Pwd=wyg154511LHL;TrustServerCertificate=true; 
      - App__CorsOrigins=http://localhost:8081,http://localhost:4200

volumes:
  hostapi_logs:
  hostapi_sysfiles:
  hostapi_fastreport:

networks:
  my_net:
    driver: overlay

