/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ArticleBasicsOutput
 */
export interface ArticleBasicsOutput {

    /**
     * 文章ID
     *
     * @type {string}
     * @memberof ArticleBasicsOutput
     */
    id?: string;

    /**
     * 封面图
     *
     * @type {string}
     * @memberof ArticleBasicsOutput
     */
    cover?: string | null;

    /**
     * 类型
     *
     * @type {number}
     * @memberof ArticleBasicsOutput
     */
    type?: number;

    /**
     * 标题
     *
     * @type {string}
     * @memberof ArticleBasicsOutput
     */
    title?: string | null;

    /**
     * 发布时间
     *
     * @type {Date}
     * @memberof ArticleBasicsOutput
     */
    publishTime?: Date | null;
}
