/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Gender } from './gender';
 /**
 * 
 *
 * @export
 * @interface AuthAccountPageOutput
 */
export interface AuthAccountPageOutput {

    /**
     * 主键
     *
     * @type {string}
     * @memberof AuthAccountPageOutput
     */
    id?: string | null;

    /**
     * 昵称
     *
     * @type {string}
     * @memberof AuthAccountPageOutput
     */
    name?: string | null;

    /**
     * @type {Gender}
     * @memberof AuthAccountPageOutput
     */
    gender?: Gender;

    /**
     * 授权类型
     *
     * @type {string}
     * @memberof AuthAccountPageOutput
     */
    type?: string | null;

    /**
     * 是否是博主
     *
     * @type {boolean}
     * @memberof AuthAccountPageOutput
     */
    isBlogger?: boolean;

    /**
     * 头像
     *
     * @type {string}
     * @memberof AuthAccountPageOutput
     */
    avatar?: string | null;

    /**
     * 注册时间
     *
     * @type {Date}
     * @memberof AuthAccountPageOutput
     */
    createdTime?: Date | null;
}
