/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AvailabilityStatus } from './availability-status';
 /**
 * 
 *
 * @export
 * @interface AvailabilityDto
 */
export interface AvailabilityDto {

    /**
     * @type {string}
     * @memberof AvailabilityDto
     */
    id?: string | null;

    /**
     * @type {string}
     * @memberof AvailabilityDto
     */
    gId?: string | null;

    /**
     * @type {AvailabilityStatus}
     * @memberof AvailabilityDto
     */
    status?: AvailabilityStatus;
}
