/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CommentPageQueryInput
 */
export interface CommentPageQueryInput {

    /**
     * @type {number}
     * @memberof CommentPageQueryInput
     */
    pageNo?: number;

    /**
     * @type {number}
     * @memberof CommentPageQueryInput
     */
    pageSize?: number;

    /**
     * 对应模块ID或评论ID（null表留言，0代表友链的评论）
     *
     * @type {string}
     * @memberof CommentPageQueryInput
     */
    id?: string | null;
}
