/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AvailabilityStatus } from './availability-status';
import { CoverType } from './cover-type';
 /**
 * 
 *
 * @export
 * @interface CreateOrUpdateAlbumsInput
 */
export interface CreateOrUpdateAlbumsInput {

    /**
     * @type {string}
     * @memberof CreateOrUpdateAlbumsInput
     */
    id?: string | null;

    /**
     * 相册名称
     *
     * @type {string}
     * @memberof CreateOrUpdateAlbumsInput
     */
    name: string;

    /**
     * 封面图
     *
     * @type {string}
     * @memberof CreateOrUpdateAlbumsInput
     */
    cover: string;

    /**
     * @type {CoverType}
     * @memberof CreateOrUpdateAlbumsInput
     */
    type?: CoverType;

    /**
     * @type {AvailabilityStatus}
     * @memberof CreateOrUpdateAlbumsInput
     */
    status?: AvailabilityStatus;

    /**
     * 排序值（值越小越靠前）
     *
     * @type {number}
     * @memberof CreateOrUpdateAlbumsInput
     */
    sort: number;

    /**
     * 备注
     *
     * @type {string}
     * @memberof CreateOrUpdateAlbumsInput
     */
    remark?: string | null;

    /**
     * 是否可见
     *
     * @type {boolean}
     * @memberof CreateOrUpdateAlbumsInput
     */
    isVisible?: boolean;
}
