/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { FileType } from './file-type';
 /**
 * 
 *
 * @export
 * @interface FileInfoOutput
 */
export interface FileInfoOutput {

    /**
     * @type {string}
     * @memberof FileInfoOutput
     */
    id?: string;

    /**
     * 父级Id
     *
     * @type {string}
     * @memberof FileInfoOutput
     */
    parentId?: string | null;

    /**
     * 文件显示名称，例如文件名为  open.jpg，显示名称为： open_编码规则
     *
     * @type {string}
     * @memberof FileInfoOutput
     */
    fileDisplayName?: string | null;

    /**
     * 文件原始名称
     *
     * @type {string}
     * @memberof FileInfoOutput
     */
    fileName?: string | null;

    /**
     * 文件扩展名
     *
     * @type {string}
     * @memberof FileInfoOutput
     */
    fileExt?: string | null;

    /**
     * 文件类型
     *
     * @type {string}
     * @memberof FileInfoOutput
     */
    contentType?: string | null;

    /**
     * 文件路径
     *
     * @type {string}
     * @memberof FileInfoOutput
     */
    filePath?: string | null;

    /**
     * 文件大小，字节
     *
     * @type {string}
     * @memberof FileInfoOutput
     */
    fileSize?: string | null;

    /**
     * @type {FileType}
     * @memberof FileInfoOutput
     */
    fileType?: FileType;

    /**
     * 文件类型名称
     *
     * @type {string}
     * @memberof FileInfoOutput
     */
    fileTypeString?: string | null;

    /**
     * 编码  (记录文件的层次结构关系)  Example: \"00001.00042.00005\". 这是租户的唯一代码。 当然可以进行修改
     *
     * @type {string}
     * @memberof FileInfoOutput
     */
    code?: string | null;

    /**
     * 是否是文件夹
     *
     * @type {boolean}
     * @memberof FileInfoOutput
     */
    isFolder?: boolean;

    /**
     * Ip 地址
     *
     * @type {string}
     * @memberof FileInfoOutput
     */
    fileIpAddress?: string | null;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof FileInfoOutput
     */
    creationTime?: Date | null;
}
