/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TalkDetailOutput
 */
export interface TalkDetailOutput {

    /**
     * @type {string}
     * @memberof TalkDetailOutput
     */
    id?: string;

    /**
     * 是否置顶
     *
     * @type {boolean}
     * @memberof TalkDetailOutput
     */
    isTop?: boolean;

    /**
     * 内容
     *
     * @type {string}
     * @memberof TalkDetailOutput
     */
    content?: string | null;

    /**
     * 图片
     *
     * @type {string}
     * @memberof TalkDetailOutput
     */
    images?: string | null;

    /**
     * 是否已点赞
     *
     * @type {boolean}
     * @memberof TalkDetailOutput
     */
    isPraise?: boolean;

    /**
     * 点赞数量
     *
     * @type {number}
     * @memberof TalkDetailOutput
     */
    upvote?: number;

    /**
     * 评论数量
     *
     * @type {number}
     * @memberof TalkDetailOutput
     */
    comments?: number;

    /**
     * 发布时间
     *
     * @type {Date}
     * @memberof TalkDetailOutput
     */
    createdTime?: Date | null;

    /**
     * 是否允许评论
     *
     * @type {boolean}
     * @memberof TalkDetailOutput
     */
    isAllowComments?: boolean;
}
