/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AvailabilityStatus } from './availability-status';
 /**
 * 
 *
 * @export
 * @interface UpdateCategoryInput
 */
export interface UpdateCategoryInput {

    /**
     * 栏目名称
     *
     * @type {string}
     * @memberof UpdateCategoryInput
     */
    name?: string | null;

    /**
     * 父级id
     *
     * @type {number}
     * @memberof UpdateCategoryInput
     */
    parentId?: number | null;

    /**
     * 封面图
     *
     * @type {string}
     * @memberof UpdateCategoryInput
     */
    cover?: string | null;

    /**
     * @type {AvailabilityStatus}
     * @memberof UpdateCategoryInput
     */
    status?: AvailabilityStatus;

    /**
     * 排序值（值越小越靠前）
     *
     * @type {number}
     * @memberof UpdateCategoryInput
     */
    sort?: number;

    /**
     * 备注
     *
     * @type {string}
     * @memberof UpdateCategoryInput
     */
    remark?: string | null;

    /**
     * 栏目ID
     *
     * @type {string}
     * @memberof UpdateCategoryInput
     */
    id: string;
}
