/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AvailabilityStatus } from './availability-status';
 /**
 * 
 *
 * @export
 * @interface UpdateOrgInput
 */
export interface UpdateOrgInput {

    /**
     * 父级Id
     *
     * @type {string}
     * @memberof UpdateOrgInput
     */
    parentId?: string | null;

    /**
     * 部门名称
     *
     * @type {string}
     * @memberof UpdateOrgInput
     */
    name: string;

    /**
     * 部门编码
     *
     * @type {string}
     * @memberof UpdateOrgInput
     */
    code?: string | null;

    /**
     * @type {AvailabilityStatus}
     * @memberof UpdateOrgInput
     */
    status?: AvailabilityStatus;

    /**
     * 排序值（值越小越靠前）
     *
     * @type {number}
     * @memberof UpdateOrgInput
     */
    sort?: number;

    /**
     * 备注
     *
     * @type {string}
     * @memberof UpdateOrgInput
     */
    remark?: string | null;

    /**
     * 部门Id
     *
     * @type {string}
     * @memberof UpdateOrgInput
     */
    id?: string | null;
}
