/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Gender } from './gender';
 /**
 * 
 *
 * @export
 * @interface UpdateCurrentUserInput
 */
export interface UpdateCurrentUserInput {

    /**
     * 姓名
     *
     * @type {string}
     * @memberof UpdateCurrentUserInput
     */
    name: string;

    /**
     * @type {Gender}
     * @memberof UpdateCurrentUserInput
     */
    gender?: Gender;

    /**
     * 昵称
     *
     * @type {string}
     * @memberof UpdateCurrentUserInput
     */
    nickName?: string | null;

    /**
     * 生日
     *
     * @type {Date}
     * @memberof UpdateCurrentUserInput
     */
    birthday?: Date | null;

    /**
     * 手机号码
     *
     * @type {string}
     * @memberof UpdateCurrentUserInput
     */
    mobile?: string | null;

    /**
     * 邮箱
     *
     * @type {string}
     * @memberof UpdateCurrentUserInput
     */
    email?: string | null;
}
