/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AvailabilityStatus } from './availability-status';
 /**
 * 
 *
 * @export
 * @interface UpdateSysRoleInput
 */
export interface UpdateSysRoleInput {

    /**
     * 角色名称
     *
     * @type {string}
     * @memberof UpdateSysRoleInput
     */
    name: string;

    /**
     * @type {AvailabilityStatus}
     * @memberof UpdateSysRoleInput
     */
    status?: AvailabilityStatus;

    /**
     * 角色编码
     *
     * @type {string}
     * @memberof UpdateSysRoleInput
     */
    code: string;

    /**
     * 排序值
     *
     * @type {number}
     * @memberof UpdateSysRoleInput
     */
    sort?: number;

    /**
     * 备注
     *
     * @type {string}
     * @memberof UpdateSysRoleInput
     */
    remark?: string | null;

    /**
     * 授权按钮菜单Id
     *
     * @type {Array<string>}
     * @memberof UpdateSysRoleInput
     */
    menus: Array<string>;

    /**
     * 角色Id
     *
     * @type {string}
     * @memberof UpdateSysRoleInput
     */
    id?: string | null;
}
