/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UploadFileOutput
 */
export interface UploadFileOutput {

    /**
     * 文件名
     *
     * @type {string}
     * @memberof UploadFileOutput
     */
    name?: string | null;

    /**
     * 附件链接
     *
     * @type {string}
     * @memberof UploadFileOutput
     */
    url?: string | null;
}
