/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AvailabilityStatus } from './availability-status';
import { Gender } from './gender';
 /**
 * 
 *
 * @export
 * @interface UserPageOutput
 */
export interface UserPageOutput {

    /**
     * @type {string}
     * @memberof UserPageOutput
     */
    id?: string | null;

    /**
     * 姓名
     *
     * @type {string}
     * @memberof UserPageOutput
     */
    name?: string | null;

    /**
     * @type {AvailabilityStatus}
     * @memberof UserPageOutput
     */
    status?: AvailabilityStatus;

    /**
     * 账户名
     *
     * @type {string}
     * @memberof UserPageOutput
     */
    userName?: string | null;

    /**
     * 生日
     *
     * @type {Date}
     * @memberof UserPageOutput
     */
    birthday?: Date | null;

    /**
     * 手机号码
     *
     * @type {string}
     * @memberof UserPageOutput
     */
    mobile?: string | null;

    /**
     * @type {Gender}
     * @memberof UserPageOutput
     */
    gender?: Gender;

    /**
     * 昵称
     *
     * @type {string}
     * @memberof UserPageOutput
     */
    nickName?: string | null;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof UserPageOutput
     */
    createdTime?: Date | null;

    /**
     * 邮箱
     *
     * @type {string}
     * @memberof UserPageOutput
     */
    email?: string | null;
}
