/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Gender } from './gender';
 /**
 * 
 *
 * @export
 * @interface ZUserInfoOutput
 */
export interface ZUserInfoOutput {

    /**
     * 姓名
     *
     * @type {string}
     * @memberof ZUserInfoOutput
     */
    name?: string | null;

    /**
     * 账户名
     *
     * @type {string}
     * @memberof ZUserInfoOutput
     */
    userName?: string | null;

    /**
     * 头像
     *
     * @type {string}
     * @memberof ZUserInfoOutput
     */
    avatar?: string | null;

    /**
     * 生日
     *
     * @type {Date}
     * @memberof ZUserInfoOutput
     */
    birthday?: Date | null;

    /**
     * 邮箱
     *
     * @type {string}
     * @memberof ZUserInfoOutput
     */
    email?: string | null;

    /**
     * @type {Gender}
     * @memberof ZUserInfoOutput
     */
    gender?: Gender;

    /**
     * 昵称
     *
     * @type {string}
     * @memberof ZUserInfoOutput
     */
    nickName?: string | null;

    /**
     * 备注
     *
     * @type {string}
     * @memberof ZUserInfoOutput
     */
    remark?: string | null;

    /**
     * 最后登录ip
     *
     * @type {string}
     * @memberof ZUserInfoOutput
     */
    lastLoginIp?: string | null;

    /**
     * 最后登录IP所属地址
     *
     * @type {string}
     * @memberof ZUserInfoOutput
     */
    lastLoginAddress?: string | null;

    /**
     * 手机号码
     *
     * @type {string}
     * @memberof ZUserInfoOutput
     */
    mobile?: string | null;

    /**
     * 机构id
     *
     * @type {string}
     * @memberof ZUserInfoOutput
     */
    orgId?: string | null;

    /**
     * 机构名称
     *
     * @type {string}
     * @memberof ZUserInfoOutput
     */
    orgName?: string | null;

    /**
     * 授权按钮
     *
     * @type {Array<string>}
     * @memberof ZUserInfoOutput
     */
    authBtnList?: Array<string> | null;
}
