/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AvailabilityStatus } from './availability-status';
import { Gender } from './gender';
 /**
 * 
 *
 * @export
 * @interface AddUserInput
 */
export interface AddUserInput {

    /**
     * 用户名
     *
     * @type {string}
     * @memberof AddUserInput
     */
    userName: string;

    /**
     * 姓名
     *
     * @type {string}
     * @memberof AddUserInput
     */
    name: string;

    /**
     * @type {Gender}
     * @memberof AddUserInput
     */
    gender?: Gender;

    /**
     * 组织机构id
     *
     * @type {string}
     * @memberof AddUserInput
     */
    orgId?: string | null;

    /**
     * 昵称
     *
     * @type {string}
     * @memberof AddUserInput
     */
    nickName?: string | null;

    /**
     * 生日
     *
     * @type {Date}
     * @memberof AddUserInput
     */
    birthday?: Date | null;

    /**
     * 手机号码
     *
     * @type {string}
     * @memberof AddUserInput
     */
    mobile?: string | null;

    /**
     * @type {AvailabilityStatus}
     * @memberof AddUserInput
     */
    status?: AvailabilityStatus;

    /**
     * 邮箱
     *
     * @type {string}
     * @memberof AddUserInput
     */
    email?: string | null;

    /**
     * 备注
     *
     * @type {string}
     * @memberof AddUserInput
     */
    remark?: string | null;

    /**
     * 角色
     *
     * @type {Array<string>}
     * @memberof AddUserInput
     */
    roles?: Array<string> | null;
}
