/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AddLinkOutput
 */
export interface AddLinkOutput {

    /**
     * 网站名称
     *
     * @type {string}
     * @memberof AddLinkOutput
     */
    siteName: string;

    /**
     * 网站链接
     *
     * @type {string}
     * @memberof AddLinkOutput
     */
    link: string;

    /**
     * 网站logo
     *
     * @type {string}
     * @memberof AddLinkOutput
     */
    logo: string;

    /**
     * 对方博客友链的地址
     *
     * @type {string}
     * @memberof AddLinkOutput
     */
    url: string;

    /**
     * 网站介绍
     *
     * @type {string}
     * @memberof AddLinkOutput
     */
    remark: string;
}
