/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AvailabilityStatus } from './availability-status';
import { CoverType } from './cover-type';
 /**
 * 
 *
 * @export
 * @interface AlbumsPageOutput
 */
export interface AlbumsPageOutput {

    /**
     * 相册ID
     *
     * @type {string}
     * @memberof AlbumsPageOutput
     */
    id?: string;

    /**
     * 名称
     *
     * @type {string}
     * @memberof AlbumsPageOutput
     */
    name?: string | null;

    /**
     * @type {CoverType}
     * @memberof AlbumsPageOutput
     */
    type?: CoverType;

    /**
     * @type {AvailabilityStatus}
     * @memberof AlbumsPageOutput
     */
    status?: AvailabilityStatus;

    /**
     * 是否显示
     *
     * @type {boolean}
     * @memberof AlbumsPageOutput
     */
    isVisible?: boolean;

    /**
     * 排序
     *
     * @type {number}
     * @memberof AlbumsPageOutput
     */
    sort?: number;

    /**
     * 备注
     *
     * @type {string}
     * @memberof AlbumsPageOutput
     */
    remark?: string | null;

    /**
     * 封面
     *
     * @type {string}
     * @memberof AlbumsPageOutput
     */
    cover?: string | null;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof AlbumsPageOutput
     */
    createdTime?: Date | null;
}
