/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CoverType } from './cover-type';
 /**
 * 
 *
 * @export
 * @interface AlbumsPageQueryInput
 */
export interface AlbumsPageQueryInput {

    /**
     * @type {number}
     * @memberof AlbumsPageQueryInput
     */
    pageNo?: number;

    /**
     * @type {number}
     * @memberof AlbumsPageQueryInput
     */
    pageSize?: number;

    /**
     * 相册名称
     *
     * @type {string}
     * @memberof AlbumsPageQueryInput
     */
    name?: string | null;

    /**
     * @type {CoverType}
     * @memberof AlbumsPageQueryInput
     */
    type?: CoverType;
}
