/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import type { ImgInfo } from './img-info';
 /**
 * 
 *
 * @export
 * @interface BlogSetting
 */
export interface BlogSetting {

    /**
     * @type {Array<ImgInfo>}
     * @memberof BlogSetting
     */
    logo?: Array<ImgInfo> | null;

    /**
     * @type {string}
     * @memberof BlogSetting
     */
    logoUrl?: string | null;

    /**
     * @type {Array<ImgInfo>}
     * @memberof BlogSetting
     */
    favicon?: Array<ImgInfo> | null;

    /**
     * @type {string}
     * @memberof BlogSetting
     */
    faviconUrl?: string | null;

    /**
     * @type {boolean}
     * @memberof BlogSetting
     */
    isRewards?: boolean | null;

    /**
     * @type {Array<ImgInfo>}
     * @memberof BlogSetting
     */
    aliPay?: Array<ImgInfo> | null;

    /**
     * @type {string}
     * @memberof BlogSetting
     */
    aliPayUrl?: string | null;

    /**
     * @type {Array<ImgInfo>}
     * @memberof BlogSetting
     */
    wxPay?: Array<ImgInfo> | null;

    /**
     * @type {string}
     * @memberof BlogSetting
     */
    wxPayUrl?: string | null;

    /**
     * @type {boolean}
     * @memberof BlogSetting
     */
    isAllowMessage?: boolean | null;

    /**
     * @type {boolean}
     * @memberof BlogSetting
     */
    isAllowComments?: boolean | null;

    /**
     * @type {string}
     * @memberof BlogSetting
     */
    announcement?: string | null;

    /**
     * @type {string}
     * @memberof BlogSetting
     */
    siteName?: string | null;

    /**
     * @type {string}
     * @memberof BlogSetting
     */
    motto?: string | null;

    /**
     * @type {Date}
     * @memberof BlogSetting
     */
    runTime?: Date;

    /**
     * @type {string}
     * @memberof BlogSetting
     */
    copyright?: string | null;

    /**
     * @type {string}
     * @memberof BlogSetting
     */
    description?: string | null;

    /**
     * @type {string}
     * @memberof BlogSetting
     */
    keyword?: string | null;

    /**
     * @type {string}
     * @memberof BlogSetting
     */
    filing?: string | null;
}
