/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import type { BlogSetting } from './blog-setting';
import type { BloggerInfo } from './blogger-info';
 /**
 * 
 *
 * @export
 * @interface BlogOutput
 */
export interface BlogOutput {

    /**
     * @type {BlogSetting}
     * @memberof BlogOutput
     */
    site?: BlogSetting;

    /**
     * @type {BloggerInfo}
     * @memberof BlogOutput
     */
    info?: BloggerInfo;

    /**
     * 各个页面封面图
     *
     * @type {{ [key: string]: Array<string>; }}
     * @memberof BlogOutput
     */
    covers?: { [key: string]: Array<string>; } | null;
}
