/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ChangePasswordOutput
 */
export interface ChangePasswordOutput {

    /**
     * 原密码
     *
     * @type {string}
     * @memberof ChangePasswordOutput
     */
    originalPwd: string;

    /**
     * 新密码
     *
     * @type {string}
     * @memberof ChangePasswordOutput
     */
    password: string;
}
