/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AvailabilityStatus } from './availability-status';
 /**
 * 
 *
 * @export
 * @interface CreateOrUpdateTalksInput
 */
export interface CreateOrUpdateTalksInput {

    /**
     * @type {string}
     * @memberof CreateOrUpdateTalksInput
     */
    id?: string | null;

    /**
     * 是否置顶
     *
     * @type {boolean}
     * @memberof CreateOrUpdateTalksInput
     */
    isTop?: boolean;

    /**
     * 说说正文
     *
     * @type {string}
     * @memberof CreateOrUpdateTalksInput
     */
    content: string;

    /**
     * 图片
     *
     * @type {string}
     * @memberof CreateOrUpdateTalksInput
     */
    images?: string | null;

    /**
     * 是否允许评论
     *
     * @type {boolean}
     * @memberof CreateOrUpdateTalksInput
     */
    isAllowComments?: boolean;

    /**
     * @type {AvailabilityStatus}
     * @memberof CreateOrUpdateTalksInput
     */
    status?: AvailabilityStatus;
}
