/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AvailabilityStatus } from './availability-status';
 /**
 * 
 *
 * @export
 * @interface CreateOrUpdateTagInput
 */
export interface CreateOrUpdateTagInput {

    /**
     * 文章ID
     *
     * @type {string}
     * @memberof CreateOrUpdateTagInput
     */
    id?: string | null;

    /**
     * 标签名称
     *
     * @type {string}
     * @memberof CreateOrUpdateTagInput
     */
    name: string;

    /**
     * 封面图
     *
     * @type {string}
     * @memberof CreateOrUpdateTagInput
     */
    cover: string;

    /**
     * 标签颜色
     *
     * @type {string}
     * @memberof CreateOrUpdateTagInput
     */
    color?: string | null;

    /**
     * 标签图标
     *
     * @type {string}
     * @memberof CreateOrUpdateTagInput
     */
    icon?: string | null;

    /**
     * @type {AvailabilityStatus}
     * @memberof CreateOrUpdateTagInput
     */
    status?: AvailabilityStatus;

    /**
     * 排序值（值越小越靠前）
     *
     * @type {number}
     * @memberof CreateOrUpdateTagInput
     */
    sort: number;

    /**
     * 备注
     *
     * @type {string}
     * @memberof CreateOrUpdateTagInput
     */
    remark?: string | null;
}
