/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AvailabilityStatus } from './availability-status';
 /**
 * 
 *
 * @export
 * @interface CreateOrUpdateFriendInput
 */
export interface CreateOrUpdateFriendInput {

    /**
     * @type {string}
     * @memberof CreateOrUpdateFriendInput
     */
    id?: string | null;

    /**
     * 网站名称
     *
     * @type {string}
     * @memberof CreateOrUpdateFriendInput
     */
    siteName: string;

    /**
     * 网站链接
     *
     * @type {string}
     * @memberof CreateOrUpdateFriendInput
     */
    link: string;

    /**
     * 网站logo
     *
     * @type {string}
     * @memberof CreateOrUpdateFriendInput
     */
    logo: string;

    /**
     * 对方博客友链的地址
     *
     * @type {string}
     * @memberof CreateOrUpdateFriendInput
     */
    url?: string | null;

    /**
     * 是否忽略对方站点是否存在本站链接
     *
     * @type {boolean}
     * @memberof CreateOrUpdateFriendInput
     */
    isIgnoreCheck?: boolean;

    /**
     * 备注
     *
     * @type {string}
     * @memberof CreateOrUpdateFriendInput
     */
    remark?: string | null;

    /**
     * 排序值（值越小越靠前）
     *
     * @type {number}
     * @memberof CreateOrUpdateFriendInput
     */
    sort: number;

    /**
     * @type {AvailabilityStatus}
     * @memberof CreateOrUpdateFriendInput
     */
    status?: AvailabilityStatus;
}
