/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CustomConfigDetailOutput
 */
export interface CustomConfigDetailOutput {

    /**
     * 表单渲染Json
     *
     * @type {string}
     * @memberof CustomConfigDetailOutput
     */
    formJson?: string | null;

    /**
     * 表单数据
     *
     * @type {string}
     * @memberof CustomConfigDetailOutput
     */
    dataJson?: string | null;

    /**
     * 配置项Id
     *
     * @type {string}
     * @memberof CustomConfigDetailOutput
     */
    itemId?: string | null;
}
