/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CustomConfigSetJsonInput
 */
export interface CustomConfigSetJsonInput {

    /**
     * 自定义配置ID
     *
     * @type {string}
     * @memberof CustomConfigSetJsonInput
     */
    id: string;

    /**
     * 表单设计
     *
     * @type {string}
     * @memberof CustomConfigSetJsonInput
     */
    json: string;
}
