/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AvailabilityStatus } from './availability-status';
import { MenuType } from './menu-type';
 /**
 * 
 *
 * @export
 * @interface MenuPageOutput
 */
export interface MenuPageOutput {

    /**
     * 菜单Id
     *
     * @type {string}
     * @memberof MenuPageOutput
     */
    id?: string;

    /**
     * 菜单名称
     *
     * @type {string}
     * @memberof MenuPageOutput
     */
    name?: string | null;

    /**
     * 权限标识
     *
     * @type {string}
     * @memberof MenuPageOutput
     */
    code?: string | null;

    /**
     * 菜单图标
     *
     * @type {string}
     * @memberof MenuPageOutput
     */
    icon?: string | null;

    /**
     * @type {MenuType}
     * @memberof MenuPageOutput
     */
    type?: MenuType;

    /**
     * 路由地址
     *
     * @type {string}
     * @memberof MenuPageOutput
     */
    path?: string | null;

    /**
     * 组件路径
     *
     * @type {string}
     * @memberof MenuPageOutput
     */
    component?: string | null;

    /**
     * @type {AvailabilityStatus}
     * @memberof MenuPageOutput
     */
    status?: AvailabilityStatus;

    /**
     * 排序值（值越小越靠前）
     *
     * @type {number}
     * @memberof MenuPageOutput
     */
    sort?: number;

    /**
     * 创建时间
     *
     * @type {Date}
     * @memberof MenuPageOutput
     */
    createdTime?: Date | null;

    /**
     * 子菜单
     *
     * @type {Array<MenuPageOutput>}
     * @memberof MenuPageOutput
     */
    children?: Array<MenuPageOutput> | null;
}
