/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AvailabilityStatus } from './availability-status';
import { MenuType } from './menu-type';
 /**
 * 
 *
 * @export
 * @interface Menu
 */
export interface Menu {

    /**
     * @type {string}
     * @memberof Menu
     */
    id?: string;

    /**
     * @type {string}
     * @memberof Menu
     */
    creatorId?: string | null;

    /**
     * @type {Date}
     * @memberof Menu
     */
    creationTime?: Date | null;

    /**
     * @type {string}
     * @memberof Menu
     */
    deleterId?: string | null;

    /**
     * @type {Date}
     * @memberof Menu
     */
    deletionTime?: Date | null;

    /**
     * @type {boolean}
     * @memberof Menu
     */
    isDeleted?: boolean | null;

    /**
     * @type {string}
     * @memberof Menu
     */
    name?: string | null;

    /**
     * @type {MenuType}
     * @memberof Menu
     */
    type?: MenuType;

    /**
     * @type {string}
     * @memberof Menu
     */
    code?: string | null;

    /**
     * @type {string}
     * @memberof Menu
     */
    parentId?: string | null;

    /**
     * @type {string}
     * @memberof Menu
     */
    routeName?: string | null;

    /**
     * @type {string}
     * @memberof Menu
     */
    path?: string | null;

    /**
     * @type {string}
     * @memberof Menu
     */
    component?: string | null;

    /**
     * @type {string}
     * @memberof Menu
     */
    redirect?: string | null;

    /**
     * @type {string}
     * @memberof Menu
     */
    icon?: string | null;

    /**
     * @type {boolean}
     * @memberof Menu
     */
    isIframe?: boolean;

    /**
     * @type {string}
     * @memberof Menu
     */
    link?: string | null;

    /**
     * @type {boolean}
     * @memberof Menu
     */
    isVisible?: boolean;

    /**
     * @type {boolean}
     * @memberof Menu
     */
    isKeepAlive?: boolean;

    /**
     * @type {boolean}
     * @memberof Menu
     */
    isFixed?: boolean;

    /**
     * @type {AvailabilityStatus}
     * @memberof Menu
     */
    status?: AvailabilityStatus;

    /**
     * @type {number}
     * @memberof Menu
     */
    sort?: number;

    /**
     * @type {string}
     * @memberof Menu
     */
    remark?: string | null;

    /**
     * @type {Array<Menu>}
     * @memberof Menu
     */
    children?: Array<Menu> | null;
}
