/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AvailabilityStatus } from './availability-status';
import { MenuType } from './menu-type';
 /**
 * 
 *
 * @export
 * @interface MenuDetailOutput
 */
export interface MenuDetailOutput {

    /**
     * 菜单Id
     *
     * @type {string}
     * @memberof MenuDetailOutput
     */
    id?: string;

    /**
     * 菜单名称
     *
     * @type {string}
     * @memberof MenuDetailOutput
     */
    name?: string | null;

    /**
     * 父级id
     *
     * @type {string}
     * @memberof MenuDetailOutput
     */
    parentId?: string | null;

    /**
     * @type {AvailabilityStatus}
     * @memberof MenuDetailOutput
     */
    status?: AvailabilityStatus;

    /**
     * 权限标识
     *
     * @type {string}
     * @memberof MenuDetailOutput
     */
    code?: string | null;

    /**
     * 排序
     *
     * @type {number}
     * @memberof MenuDetailOutput
     */
    sort?: number;

    /**
     * 组件路径
     *
     * @type {string}
     * @memberof MenuDetailOutput
     */
    component?: string | null;

    /**
     * 图标
     *
     * @type {string}
     * @memberof MenuDetailOutput
     */
    icon?: string | null;

    /**
     * 是否固定
     *
     * @type {boolean}
     * @memberof MenuDetailOutput
     */
    isFixed?: boolean;

    /**
     * 是否内嵌
     *
     * @type {boolean}
     * @memberof MenuDetailOutput
     */
    isIframe?: boolean;

    /**
     * 是否缓存
     *
     * @type {boolean}
     * @memberof MenuDetailOutput
     */
    isKeepAlive?: boolean;

    /**
     * 是否可见
     *
     * @type {boolean}
     * @memberof MenuDetailOutput
     */
    isVisible?: boolean;

    /**
     * 外链
     *
     * @type {string}
     * @memberof MenuDetailOutput
     */
    link?: string | null;

    /**
     * 备注
     *
     * @type {string}
     * @memberof MenuDetailOutput
     */
    remark?: string | null;

    /**
     * 路由地址
     *
     * @type {string}
     * @memberof MenuDetailOutput
     */
    path?: string | null;

    /**
     * 重定向地址
     *
     * @type {string}
     * @memberof MenuDetailOutput
     */
    redirect?: string | null;

    /**
     * 路由名称
     *
     * @type {string}
     * @memberof MenuDetailOutput
     */
    routeName?: string | null;

    /**
     * @type {MenuType}
     * @memberof MenuDetailOutput
     */
    type?: MenuType;
}
