/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AvailabilityStatus } from './availability-status';
 /**
 * 
 *
 * @export
 * @interface OAuthAccountDetailOutput
 */
export interface OAuthAccountDetailOutput {

    /**
     * 用户ID
     *
     * @type {string}
     * @memberof OAuthAccountDetailOutput
     */
    id?: string | null;

    /**
     * 昵称
     *
     * @type {string}
     * @memberof OAuthAccountDetailOutput
     */
    nickName?: string | null;

    /**
     * 头像
     *
     * @type {string}
     * @memberof OAuthAccountDetailOutput
     */
    avatar?: string | null;

    /**
     * @type {AvailabilityStatus}
     * @memberof OAuthAccountDetailOutput
     */
    status?: AvailabilityStatus;

    /**
     * 网站链接
     *
     * @type {string}
     * @memberof OAuthAccountDetailOutput
     */
    link?: string | null;

    /**
     * logo
     *
     * @type {string}
     * @memberof OAuthAccountDetailOutput
     */
    logo?: string | null;

    /**
     * 网站名称
     *
     * @type {string}
     * @memberof OAuthAccountDetailOutput
     */
    siteName?: string | null;

    /**
     * 对方博客友链地址
     *
     * @type {string}
     * @memberof OAuthAccountDetailOutput
     */
    url?: string | null;

    /**
     * 网站介绍
     *
     * @type {string}
     * @memberof OAuthAccountDetailOutput
     */
    remark?: string | null;
}
