/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PicturesPageQueryInput
 */
export interface PicturesPageQueryInput {

    /**
     * @type {number}
     * @memberof PicturesPageQueryInput
     */
    pageNo?: number;

    /**
     * @type {number}
     * @memberof PicturesPageQueryInput
     */
    pageSize?: number;

    /**
     * 相册ID
     *
     * @type {string}
     * @memberof PicturesPageQueryInput
     */
    id?: string;
}
