/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PictureOutput
 */
export interface PictureOutput {

    /**
     * 图片ID
     *
     * @type {string}
     * @memberof PictureOutput
     */
    id?: string;

    /**
     * 图片地址
     *
     * @type {string}
     * @memberof PictureOutput
     */
    url?: string | null;
}
