/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ReplyOutput
 */
export interface ReplyOutput {

    /**
     * 评论ID
     *
     * @type {string}
     * @memberof ReplyOutput
     */
    id?: string;

    /**
     * 评论内容
     *
     * @type {string}
     * @memberof ReplyOutput
     */
    content?: string | null;

    /**
     * 博主标识
     *
     * @type {boolean}
     * @memberof ReplyOutput
     */
    isBlogger?: boolean;

    /**
     * 顶级楼层评论ID
     *
     * @type {string}
     * @memberof ReplyOutput
     */
    rootId?: string | null;

    /**
     * 上级评论ID
     *
     * @type {string}
     * @memberof ReplyOutput
     */
    parentId?: string | null;

    /**
     * 当前评论人ID
     *
     * @type {string}
     * @memberof ReplyOutput
     */
    accountId?: string | null;

    /**
     * 回复人ID
     *
     * @type {string}
     * @memberof ReplyOutput
     */
    replyAccountId?: string | null;

    /**
     * 当前人昵称
     *
     * @type {string}
     * @memberof ReplyOutput
     */
    nickName?: string | null;

    /**
     * 回复人昵称
     *
     * @type {string}
     * @memberof ReplyOutput
     */
    relyNickName?: string | null;

    /**
     * 当前评论人头像
     *
     * @type {string}
     * @memberof ReplyOutput
     */
    avatar?: string | null;

    /**
     * Ip地址
     *
     * @type {string}
     * @memberof ReplyOutput
     */
    ip?: string | null;

    /**
     * 点赞数量
     *
     * @type {number}
     * @memberof ReplyOutput
     */
    praiseTotal?: number;

    /**
     * 是否已点赞
     *
     * @type {boolean}
     * @memberof ReplyOutput
     */
    isPraise?: boolean;

    /**
     * Ip所属地
     *
     * @type {string}
     * @memberof ReplyOutput
     */
    geolocation?: string | null;

    /**
     * 评论时间
     *
     * @type {Date}
     * @memberof ReplyOutput
     */
    createdTime?: Date | null;
}
