/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ResetPasswordInput
 */
export interface ResetPasswordInput {

    /**
     * @type {string}
     * @memberof ResetPasswordInput
     */
    id?: string | null;

    /**
     * 密码
     *
     * @type {string}
     * @memberof ResetPasswordInput
     */
    password: string;
}
