/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SelectOutput
 */
export interface SelectOutput {

    /**
     * @type {string}
     * @memberof SelectOutput
     */
    label?: string | null;

    /**
     * @type {any}
     * @memberof SelectOutput
     */
    value?: any | null;
}
