/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface TagsOutput
 */
export interface TagsOutput {

    /**
     * 标签ID
     *
     * @type {string}
     * @memberof TagsOutput
     */
    id?: string;

    /**
     * 图标
     *
     * @type {string}
     * @memberof TagsOutput
     */
    icon?: string | null;

    /**
     * 标签名称
     *
     * @type {string}
     * @memberof TagsOutput
     */
    name?: string | null;

    /**
     * 颜色
     *
     * @type {string}
     * @memberof TagsOutput
     */
    color?: string | null;
}
