/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AvailabilityStatus } from './availability-status';
 /**
 * 
 *
 * @export
 * @interface TalksPageOutput
 */
export interface TalksPageOutput {

    /**
     * 主键
     *
     * @type {string}
     * @memberof TalksPageOutput
     */
    id?: string;

    /**
     * @type {AvailabilityStatus}
     * @memberof TalksPageOutput
     */
    status?: AvailabilityStatus;

    /**
     * 内容
     *
     * @type {string}
     * @memberof TalksPageOutput
     */
    content?: string | null;

    /**
     * 图片
     *
     * @type {string}
     * @memberof TalksPageOutput
     */
    images?: string | null;

    /**
     * 是否允许评论
     *
     * @type {boolean}
     * @memberof TalksPageOutput
     */
    isAllowComments?: boolean;

    /**
     * 是否已点赞
     *
     * @type {boolean}
     * @memberof TalksPageOutput
     */
    isPraise?: boolean;

    /**
     * 是否置顶
     *
     * @type {boolean}
     * @memberof TalksPageOutput
     */
    isTop?: boolean;

    /**
     * 发布时间
     *
     * @type {Date}
     * @memberof TalksPageOutput
     */
    createdTime?: Date | null;
}
