/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateCustomConfigItemInput
 */
export interface UpdateCustomConfigItemInput {

    /**
     * 自定义配置Id
     *
     * @type {string}
     * @memberof UpdateCustomConfigItemInput
     */
    configId: string;

    /**
     * 配置
     *
     * @type {string}
     * @memberof UpdateCustomConfigItemInput
     */
    json: string;

    /**
     * @type {string}
     * @memberof UpdateCustomConfigItemInput
     */
    id: string;
}
