/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AvailabilityStatus } from './availability-status';
import { Gender } from './gender';
 /**
 * 
 *
 * @export
 * @interface ZUserInfo
 */
export interface ZUserInfo {

    /**
     * @type {string}
     * @memberof ZUserInfo
     */
    id?: string | null;

    /**
     * @type {string}
     * @memberof ZUserInfo
     */
    creatorId?: string | null;

    /**
     * @type {Date}
     * @memberof ZUserInfo
     */
    creationTime?: Date | null;

    /**
     * @type {string}
     * @memberof ZUserInfo
     */
    deleterId?: string | null;

    /**
     * @type {Date}
     * @memberof ZUserInfo
     */
    deletionTime?: Date | null;

    /**
     * @type {boolean}
     * @memberof ZUserInfo
     */
    isDeleted?: boolean | null;

    /**
     * @type {string}
     * @memberof ZUserInfo
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof ZUserInfo
     */
    userName?: string | null;

    /**
     * @type {string}
     * @memberof ZUserInfo
     */
    passWord?: string | null;

    /**
     * @type {string}
     * @memberof ZUserInfo
     */
    orgId?: string | null;

    /**
     * @type {Gender}
     * @memberof ZUserInfo
     */
    gender?: Gender;

    /**
     * @type {string}
     * @memberof ZUserInfo
     */
    avatar?: string | null;

    /**
     * @type {string}
     * @memberof ZUserInfo
     */
    mobile?: string | null;

    /**
     * @type {Date}
     * @memberof ZUserInfo
     */
    birthday?: Date | null;

    /**
     * @type {string}
     * @memberof ZUserInfo
     */
    email?: string | null;

    /**
     * @type {AvailabilityStatus}
     * @memberof ZUserInfo
     */
    status?: AvailabilityStatus;

    /**
     * @type {string}
     * @memberof ZUserInfo
     */
    lastLoginIp?: string | null;

    /**
     * @type {string}
     * @memberof ZUserInfo
     */
    lastLoginAddress?: string | null;

    /**
     * @type {Date}
     * @memberof ZUserInfo
     */
    lockExpired?: Date | null;
}
