/* tslint:disable */
/* eslint-disable */
/**
 * SunBlog API
 * Web API for managing By Z.SunBlog
 *
 * OpenAPI spec version: SunBlog API v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ZUserInfoDto
 */
export interface ZUserInfoDto {

    /**
     * @type {string}
     * @memberof ZUserInfoDto
     */
    id?: string | null;

    /**
     * 昵称
     *
     * @type {string}
     * @memberof ZUserInfoDto
     */
    name?: string | null;

    /**
     * 账号
     *
     * @type {string}
     * @memberof ZUserInfoDto
     */
    userName?: string | null;

    /**
     * 密码
     *
     * @type {string}
     * @memberof ZUserInfoDto
     */
    passWord?: string | null;

    /**
     * 验证码
     *
     * @type {string}
     * @memberof ZUserInfoDto
     */
    code?: string | null;
}
