version: "3.9"

volumes:
  nginx_log:
  hostbolg_logs:
  vueblog_assets:
  adminvue_assets:

configs:
  nginx_conf:
    file: ./env/nginx/nginx.conf

networks:
  fantasy_net:
    driver: bridge
    attachable: true

services:
  # hostbolg
  hostbolg:
    image: registry.cn-hangzhou.aliyuncs.com/learn-zhou/zhou-learn:hostblog
    restart: always
    networks:
      - fantasy_net
    volumes:
      - "hostbolg_logs:/app/App_Data/Logs"
    environment:
      - App__DbType=Mysql
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=80
      - App__ConnectionString__Mysql=Server=123.56.30.198;Port=3306;Database=SunBlog;Uid=root;Pwd=zhouke210;CharSet=utf8;SslMode=none;AllowPublicKeyRetrieval=True;
      - App__ConnectionString__SqlServer=Server=123.56.30.198;Port=3306;Database=SunBlog;Uid=root;Pwd=zhouke210;CharSet=utf8;SslMode=none;AllowPublicKeyRetrieval=True;
      - App__CorsOrigins=http://localhost:5100,http://localhost:5200,http://123.56.30.198:5100,http://123.56.30.198:5200

  vueblog:
    image: registry.cn-hangzhou.aliyuncs.com/learn-zhou/zhou-learn:vueblog
    networks:
      - fantasy_net
    volumes:
      - vueblog_assets:/usr/share/nginx/html/assets

  adminvue:
    image: registry.cn-hangzhou.aliyuncs.com/learn-zhou/zhou-learn:adminvue
    networks:
      - fantasy_net
    volumes:
      - adminvue_assets:/usr/share/nginx/html/assets

  nginx:
    image: nginx:1.16.1
    ports:
      - "5100:5100"
      - "5200:5200"
      - "5155:5155"
    networks:
      - fantasy_net
    volumes:
      - "nginx_log:/var/log/nginx"
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
