version: "3.9"

volumes:
  nginx_log:

configs:
  nginx_conf:
    file: ./env/nginx/nginx.conf

networks:
  fantasy_net:
    driver: bridge
    attachable: true

services:
  # hostbolg
  hostbolg:
    image: registry.cn-hangzhou.aliyuncs.com/learn-zhou/zhou-learn:hostblog
    restart: always
    networks:
      - fantasy_net
    volumes:
      - "/data/sunblog/bloghost:/app"
    environment:
      - App__DbType=Mysql
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=80
      - App__ConnectionString__Mysql=Server=47.96.234.210;Port=3306;Database=SunBlog;Uid=root;Pwd=zhouke210;CharSet=utf8;SslMode=none;AllowPublicKeyRetrieval=True;
      - App__ConnectionString__SqlServer=Server=47.96.234.210;Port=3306;Database=SunBlog;Uid=root;Pwd=zhouke210;CharSet=utf8;SslMode=none;AllowPublicKeyRetrieval=True;
      - App__CorsOrigins=http://localhost:5100,http://localhost:5200,http://47.96.234.210:5100,http://47.96.234.210:5200,http://192.168.0.7:3100,http://192.168.0.7:3200,https://sunadmin.zblog.love,https://sunblog.zblog.love

  vueblog:
    image: registry.cn-hangzhou.aliyuncs.com/learn-zhou/zhou-learn:vueblog
    restart: always
    networks:
      - fantasy_net
    depends_on:
      - hostbolg
    volumes:
      - "/data/sunblog/blogvue:/usr/share/nginx/html"

  adminvue:
    image: registry.cn-hangzhou.aliyuncs.com/learn-zhou/zhou-learn:adminvue
    restart: always
    depends_on:
      - hostbolg
    networks:
      - fantasy_net
    volumes:
      - "/data/sunblog/adminvue:/usr/share/nginx/html"

  nginx:
    image: nginx:1.16.1
    restart: always
    depends_on:
      - hostbolg
    ports:
      - "5100:5100"
      - "5200:5200"
      - "5155:5155"
    networks:
      - fantasy_net
    volumes:
      - "nginx_log:/var/log/nginx"
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
  frpc:
    image: snowdreamtech/frpc:0.54.0
    restart: always
    depends_on:
      - nginx
    network_mode: "host"
    volumes:
      - "/data/sunblog/frp/frpc.toml:/etc/frp/frpc.toml"
