name: build_action

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: login aliyun
        run: |
          sudo docker login --username=${{ secrets.ALINAME }} --password=${{ secrets.ALIPASSWORD }}  registry.cn-hangzhou.aliyuncs.com

      - name: Build Docker Image
        run: |
          image_name="${{ secrets.USERNAME }}/sunblogadmin"
          tag_name="${{secrets.VUETAG}}"
          if docker images | grep $image_name:$tag_name > /dev/null; then
           docker rmi $image_name:$tag_name
          fi
          sudo docker build -t $image_name:$tag_name -f ${{ secrets.DOCKERFILEVUE }} .

      - name: Build and push ALI
        id: ALI_build
        run: |
          image_name="${{ secrets.USERNAME }}/sunblogadmin"
          tag_name="${{secrets.VUETAG}}"
          sudo docker tag  $image_name:$tag_name registry.cn-hangzhou.aliyuncs.com/learn-zhou/zhou-learn:$tag_name
          sudo docker push registry.cn-hangzhou.aliyuncs.com/learn-zhou/zhou-learn:$tag_name

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: login aliyun
        run: |
          sudo docker login --username=${{ secrets.ALINAME }} --password=${{ secrets.ALIPASSWORD }}  registry.cn-hangzhou.aliyuncs.com
      - name: check container
        run: |
          container_name="sunblogadmin"
          tag_name="${{secrets.IMAGETAG}}"
          if docker ps -a | grep $container_name > /dev/null ; then
            echo "Docker container already exists, removing..."        
            docker stop $container_name
            docker rm $container_name
          fi
      - name: Pull ALI Image
        run: |
          image_name="${{ secrets.ALIREPOSITORY }}"
          tag_name="${{secrets.VUETAG}}"
          if docker images | grep $image_name:$tag_name > /dev/null; then
           docker rmi $image_name:$tag_name
          fi
          sudo  docker pull ${{ secrets.ALIREPOSITORY }}:$tag_name

      - name: Run Docker container
        run: |
          container_name="sunblogadmin"
          tag_name="${{secrets.VUETAG}}"
          sudo docker run --name $container_name -p ${{secrets.VUEPORT}}:80 -d ${{ secrets.ALIREPOSITORY }}:$tag_name
