name: build_action

on: workflow_dispatch

jobs:
  build_env:
    runs-on: ubuntu-latest
    steps:
      - name: login aliyun
        run: |
          sudo docker login --username=${{ secrets.ALINAME }} --password=${{ secrets.ALIPASSWORD }}  registry.cn-hangzhou.aliyuncs.com

  build_host:
    runs-on: ubuntu-latest
    needs: build_env

    steps:
      - name: 检出代码  sunbloghost
        uses: actions/checkout@v2
      - name: Build Sunblog_host Images
        run: |
          host_image_name="${{ secrets.USERNAME }}/sunbloghost"
          host_tag_name="${{secrets.HOSTIMAGETAG}}"
          if docker images | grep $host_image_name:$host_tag_name > /dev/null; then
           docker rmi $host_image_name:$host_tag_name
          fi
          echo "Current Working Directory: $(pwd)"
          cd ./src/SunBlog.AspNetCore
          echo "Current Working Directory: $(pwd)"
          sudo docker build . --force-rm=true  -t $host_image_name:$host_tag_name -f ${{ secrets.HOSTDOCKERFILE }}

      - name: Build and push ALI Host
        id: ALI_build_host
        run: |
          host_image_name="${{ secrets.USERNAME }}/sunbloghost"
          host_tag_name="${{secrets.HOSTIMAGETAG}}"
          sudo docker tag  $host_image_name:$host_tag_name registry.cn-hangzhou.aliyuncs.com/learn-zhou/zhou-learn:$host_tag_name
          sudo docker push registry.cn-hangzhou.aliyuncs.com/learn-zhou/zhou-learn:$host_tag_name

  build_admin:
    runs-on: ubuntu-latest
    needs: build_env

    steps:
      - name: 检出代码  sunblogadmin
        uses: actions/checkout@v2
      - name: Build Docker SunBlogAdmin Image
        run: |
          admin_image_name="${{ secrets.USERNAME }}/sunblogadmin"
          admin_tag_name="${{secrets.ADMINTAG}}"
          if docker images | grep $admin_image_name:$admin_tag_name > /dev/null; then
           docker rmi $admin_image_name:$admin_tag_name
          fi
          cd ./src/SunBlog.AdminVue
          sudo docker build -t $admin_image_name:$admin_tag_name --no-cache -f ${{ secrets.ADMINDOCKERFILE }} .

      - name: Build and push ALI Admin
        id: ALI_build_admin
        run: |
          admin_image_name="${{ secrets.USERNAME }}/sunblogadmin"
          admin_tag_name="${{secrets.ADMINTAG}}"
          sudo docker tag  $admin_image_name:$admin_tag_name registry.cn-hangzhou.aliyuncs.com/learn-zhou/zhou-learn:$admin_tag_name
          sudo docker push registry.cn-hangzhou.aliyuncs.com/learn-zhou/zhou-learn:$admin_tag_name

  build_vue:
    runs-on: ubuntu-latest
    needs: build_env

    steps:
      - name: 检出代码  sunblogvue
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          vue_image_name="${{ secrets.USERNAME }}/sunblogvue"
          vue_tag_name="${{secrets.VUETAG}}"
          if docker images | grep $vue_image_name:$vue_tag_name > /dev/null; then
           docker rmi $vue_image_name:$vue_tag_name
          fi
          cd ./src/SunBlog.BlogVue
          sudo docker build -t $vue_image_name:$vue_tag_name -f ${{ secrets.VUEDOCKERFILEVUE }} .

      - name: Build and push ALI Vue
        id: ALI_build_vue
        run: |
          vue_image_name="${{ secrets.USERNAME }}/sunblogvue"
          vue_tag_name="${{secrets.VUETAG}}"
          sudo docker tag  $vue_image_name:$vue_tag_name registry.cn-hangzhou.aliyuncs.com/learn-zhou/zhou-learn:$vue_tag_name
          sudo docker push registry.cn-hangzhou.aliyuncs.com/learn-zhou/zhou-learn:$vue_tag_name

  deploy:
    needs: [build_host]
    runs-on: self-hosted
    steps:
      - name: login aliyun
        run: |
          sudo docker login --username=${{ secrets.ALINAME }} --password=${{ secrets.ALIPASSWORD }}  registry.cn-hangzhou.aliyuncs.com
      - name: check container
        run: |
          container_name="hostblog"
          tag_name="${{secrets.IMAGETAG}}"
          if docker ps -a | grep $container_name > /dev/null ; then
            echo "Docker container already exists, removing..."        
            docker stop $container_name
            docker rm $container_name
          fi
      - name: Pull ALI Image
        run: |
          image_name="${{ secrets.ALIREPOSITORY }}"
          tag_name="${{secrets.IMAGETAG}}"
          if docker images | grep $image_name:$tag_name > /dev/null; then
           docker rmi $image_name:$tag_name
          fi
          sudo  docker pull ${{ secrets.ALIREPOSITORY }}:$tag_name

      - name: Run Docker container
        run: |
          container_name="hostblog"
          tag_name="${{secrets.IMAGETAG}}"
          sudo docker run --name $container_name --restart=always -itd -p ${{secrets.PORT}}:80 -e ASPNETCORE_HTTP_PORTS=80 ${{ secrets.ALIREPOSITORY }}:$tag_name
