name: compose_deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: login aliyun 登录阿里云
        run: |
          sudo docker login --username=${{ secrets.ALINAME }} --password=${{ secrets.ALIPASSWORD }}  registry.cn-hangzhou.aliyuncs.com
      - name: 检出代码  sunbloghost
        uses: actions/checkout@v2
      - name: run docker compose
        run: |
          cd docker
          # 检查服务是否存在
          if docker-compose -f docker-compose.yml ps -q sunblog > /dev/null 2>&1; then
              # 服务存在，停止并删除
              docker-compose -f docker-compose.yml stop sunblog
              docker-compose -f docker-compose.yml rm -f sunblog
              echo "Service '$SERVICE_NAME' removed."
          else
          sudo docker compose rm -f sunblog
          sleep 10
          sudo docker compose -f docker-compose.yml -p sunblog up -d
