name: compose_deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    env:
      HOSTTAG1: ${{ secrets.HOSTIMAGETAG }}
      VUETAG1: ${{ secrets.VUETAG }}
      ADMINTAG1: ${{ secrets.ADMINTAG }}
      DBYTPE1: ${{ secrets.DBYTPE }}
      CORSORIGINS1: ${{ secrets.CORSORIGINS }}
      CONNECTIONSTRINGMYSQL1: ${{ secrets.CONNECTIONSTRINGMYSQL }}
      CONNECTIONSTRINGSQLSERVER1: ${{ secrets.CONNECTIONSTRINGSQLSERVER }}
    steps:
      - name: login aliyun 登录阿里云
        run: |
          sudo docker login --username=${{ secrets.ALINAME }} --password=${{ secrets.ALIPASSWORD }}  registry.cn-hangzhou.aliyuncs.com
      - name: 检出代码  sunbloghost
        uses: actions/checkout@v2
      - name: run docker compose
        run: |
          cd docker
          # 定义环境变量
          export HOSTTAG=$HOSTIMAGETAG1
          export VUETAG=$VUETAG1
          export ADMINTAG=$ADMINTAG1
          export DBYTPE=$DBYTPE1
          export CORSORIGINS=$CORSORIGINS1
          export CONNECTIONSTRINGMYSQL=$CONNECTIONSTRINGMYSQL1
          export CONNECTIONSTRINGSQLSERVER=$CONNECTIONSTRINGSQLSERVER1
          echo $CONNECTIONSTRINGSQLSERVER1
          echo ${CONNECTIONSTRINGSQLSERVER1}
          echo ${CONNECTIONSTRINGSQLSERVER}
          # 检查服务是否存在
          if  docker-compose -p sunblog ps > /dev/null 2>&1; then
              # 服务存在，停止并删除
              docker compose -f docker-compose.yml -p sunblog down
              echo "compose sunblog removed."
              sleep 10
          fi
          sudo docker compose -f docker-compose.yml -p sunblog pull && docker compose -f docker-compose.yml -p sunblog up -d
