name: compose_deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: login aliyun 登录阿里云
        run: |
          sudo docker login --username=${{ secrets.ALINAME }} --password=${{ secrets.ALIPASSWORD }}  registry.cn-hangzhou.aliyuncs.com
      - name: 检出代码  sunbloghost
        uses: actions/checkout@v2
      - name: 定义环境变量
        run: |
          echo "${{ variables.FIRST_NAME }}"
          # 检查服务是否存在
          export HOSTTAG=${{ variables.FIRST_NAME }}
          echo $HOSTTAG
          export VUETAG="hostsunblog"
          export ADMINTAG="hostsunblog"
          export DBYTPE="hostsunblog"
          export CORSORIGINS="hostsunblog"
          export CONNECTIONSTRINGMYSQL="hostsunblog"
          export CONNECTIONSTRINGSQLSERVER="hostsunblog"

      - name: run docker compose
        run: |
          cd docker
          # 检查服务是否存在
          if  docker-compose -p sunblog ps > /dev/null 2>&1; then
              # 服务存在，停止并删除
              docker compose -f docker-compose.yml -p sunblog down
              echo "compose sunblog removed."
              sleep 10
          fi
          sudo docker compose -f docker-compose.yml -p sunblog pull && docker compose -f docker-compose.yml -p sunblog up -d
