name: compose_deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    env:
      DOTNET_VERSION: hostblog
    steps:
      - name: login aliyun 登录阿里云
        run: |
          sudo docker login --username=${{ secrets.ALINAME }} --password=${{ secrets.ALIPASSWORD }}  registry.cn-hangzhou.aliyuncs.com
      - name: 检出代码  sunbloghost
        uses: actions/checkout@v2
      - name: run docker compose
        run: |
          cd docker
          # if docker compose -f docker-compose.yml ps -q sunblog > /dev/null 2>&1; then
          #     # 服务存在，停止并删除
          #     docker compose -f docker-compose.yml stop sunblog
          #     docker compose -f docker-compose.yml rm -f sunblog
          #     echo "Service sunblog removed."
          #     sleep 10
          # fi
          sudo docker compose -f docker-compose.yml pull -p sunblog up -d
